import Head from 'next/head';
import KebabList from '../components/KebabList.jsx';
import styles from '../styles/Home.module.css';
import Featured from './../components/Featured';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tripol Kebab & Grill</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured></Featured>
      <KebabList></KebabList>
    </div>
  )
}
