import axios from 'axios';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Featured from './../components/Featured';
import KebabList from './../components/KebabList';

export default function Home({ kebabList }) {
  // console.log(kebabList);
  return (
    <div className={styles.container}>
      <Head>
        <title>Tripol Kebab & Grill</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured></Featured>
      <KebabList kebabList={kebabList}></KebabList>
    </div>
  )
}

export const getServerSideProps = async () => {
  const res = await axios.get('http://localhost:3000/api/products');
  return {
    props: {
      kebabList: res.data
    }
  }
};